listen_addrs_ipv6 = ["::0"]

[[zones]]
zone = "."

zone_type = "Forward"
stores = { type = "forward", name_servers = [
        { socket_addr = "[2400:3200::1]:443", protocol = "h3", trust_nx_responses = false, tls_dns_name = "dns.alidns.com" },
        { socket_addr = "[2400:3200:baba::1]:443", protocol = "h3", trust_nx_responses = false, tls_dns_name = "dns.alidns.com" }
    ], options = { edns0 = true, ip_strategy = "Ipv4AndIpv6", cache_size = 0, num_concurrent_reqs = 1 }}

