listen_addrs_ipv6 = ["::0"]

[[zones]]
zone = "."

zone_type = "Forward"
stores = { type = "forward", name_servers = [
        { socket_addr = "[2400:3200::1]:853", protocol = "quic", trust_nx_responses = false, tls_dns_name = "dns.alidns.com" },
        { socket_addr = "[2400:3200:baba::1]:853", protocol = "quic", trust_nx_responses = false, tls_dns_name = "dns.alidns.com" },
        { socket_addr = "223.5.5.5:853", protocol = "quic", trust_nx_responses = false, tls_dns_name = "dns.alidns.com" },
        { socket_addr = "223.6.6.6:853", protocol = "quic", trust_nx_responses = false, tls_dns_name = "dns.alidns.com" },
    ], options = { edns0 = true, ip_strategy = "Ipv4AndIpv6", cache_size = 0, num_concurrent_reqs = 4096 }}

